pipeline:
  build:
    image: python:3.6-alpine
    pull: true
    commands:
      - apk --update add build-base libffi-dev openssl-dev linux-headers
      - pip install -U pip setuptools virtualenv  # workaround
      - make install-deps
      - make test
